# serverless.yml

service: weather-forecast-lambda
provider:
  name: aws
  profile: cxnunesio
  runtime: nodejs14.x
  region: eu-west-1
  
functions:
  graphql:
    handler: src/weather-forecast/server/lambda.handler
    events:
    - http:
        path: /graphql
        method: post
        cors: true

custom:
  serverless-offline:
    port: 4000

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn

plugins:
  - serverless-webpack
  - serverless-offline